### ISSUE TITLE
Não está atualizado

### ISSUE THREAD

**Issue by GeanPOS** [chandez/Estados-Cidades-IBGE#15]
O SIDRA do IBGE não atualiza os dados periodicamente. Não é confiável pegar informações de lá.

**Comment by tavaresgerson** [comment]
Precisei dos dados também, e fiz algo semelhante, dê um olhada e vê se lhe atende: 
https://github.com/tavaresgerson/cidades-e-estados

**Comment by GeanPOS** [comment]
> Precisei dos dados também, e fiz algo semelhante, dê um olhada e vê se lhe atende:
> https://github.com/tavaresgerson/cidades-e-estados

Opa, já tinha visto seu projeto antes. Porém eu precisava dos bairros. também. Agradeço

**Comment by chandez** [comment]
> O SIDRA do IBGE não atualiza os dados periodicamente. Não é confiável pegar informações de lá.

Bem ao meu ver o IBGE é o responsável pela publicação oficial, portanto é a instituição mais confiável de se obter esses dados.

No entanto existe uma atualização de 2018, quando sobrar um tempo tento atualizar a lista.

Att.

**Comment by GeanPOS** [comment]
> > O SIDRA do IBGE não atualiza os dados periodicamente. Não é confiável pegar informações de lá.
> 
> Bem ao meu ver o IBGE é o responsável pela publicação oficial, portanto é a instituição mais confiável de se obter esses dados.
> 
> No entanto existe uma atualização de 2018, quando sobrar um tempo tento atualizar a lista.
> 
> Att.

Olá @chandez . Então, na verdade o IBGE não tem essa obrigação de manter os limites atualizados e nem de publicá-los, o que eles fazem é coletar essa informação junto a prefeitura para utilizar nas pesquisas. O IBGE divide as regiões em setores censitários, e como um setor censitário não pode ultrapassar os limites dos bairros, cidades e etc, eles tem sempre que consultar as prefeituras pra saber como estão os limites para ajustarem os setores a esses limites regionais.

Ou seja, na verdade, cabe as prefeituras e governos locais essa atualização e publicação. O IBGE só as utiliza.

Valeu!
