### ISSUE TITLE
5 novos municípios

### ISSUE THREAD

**Issue by pansardinicolas** [chandez/Estados-Cidades-IBGE#2]
Olá, seria interessante atualizar 5 novos municípios incluidos. O Brasil agora tem 5570 municípios desde 1 de janeiro de 2013.

http://oglobo.globo.com/brasil/com-5-novos-municipios-brasil-agora-tem-5570-cidades-7235803

**Comment by chandez** [comment]
Obrigado, vou atualizar no fim de semana pesquisei no IBGE e eles tem um novo site bem mais rápido com a lista [https://sidra.ibge.gov.br/territorio](https://sidra.ibge.gov.br/territorio)
